repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: v1.43.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tfsec
      - id: terraform_docs
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
